base_locale: en
locales: [en]
ignore_unused:
- "decidim.features.surveys.name"
- "decidim.features.surveys.actions.*"
- "decidim.features.surveys.settings.*"
- "decidim.surveys.admin.exports.*"
- "activemodel.attributes.survey_answer.*"
