# Configuration for request-info - https://github.com/behaviorbot/request-info
#
requestInfoReplyComment: >
  It seems like you did not give us much information about what you are trying to do here.
  We would appreciate it if you could provide us with more info about this issue/PR!

checkIssueTemplate: true

checkPullRequestTemplate: true

requestInfoOn:
  pullRequest: true
  issue: true

