sudo: required
dist: trusty

services:
  - docker
  - postgres

language: ruby

branches:
  only:
    - master

env:
  global:
    - BUNDLE_GEMFILE="$TRAVIS_BUILD_DIR/Gemfile"
    - BUNDLE_PATH="$HOME/.bundle"
    - PHANTOMJS_VERSION=2.1.1
    - PHANTOMJS_BIN="$HOME/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin/phantomjs"
  matrix:
    - GEM=. DB=postgres
    - GEM=decidim-admin DB=postgres
    - GEM=decidim-core DB=postgres
    - GEM=decidim-system DB=postgres
    - GEM=decidim-api DB=postgres
    - GEM=decidim-pages DB=postgres
    - GEM=decidim-comments DB=postgres
    - GEM=decidim-meetings DB=postgres
    - GEM=decidim-proposals DB=postgres
    - GEM=decidim-results DB=postgres

before_install:
  # Upgrade PhantomJS
  - "export PATH=$HOME/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $HOME/travis_phantomjs; mkdir -p $HOME/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $HOME/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $HOME/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $HOME/travis_phantomjs; fi"
  - "phantomjs --version"
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - gem update --system
  - yarn

bundler_args: --jobs=3 --retry=3 --deployment --path="$HOME/.bundle"

cache:
  directories:
    - $HOME/.bundle
    - $TRAVIS_BUILD_DIR/.yarn-cache
    - $TRAVIS_BUILD_DIR/node_modules
    - $BUNDLE_PATH
    - $HOME/travis_phantomjs

script:
  - cd $GEM;
  - $TRAVIS_BUILD_DIR/run_ci.sh

rvm:
  - 2.4.0

notifications:
    email: false

addons:
  postgresql: "9.4"
