sudo: required
dist: trusty

services:
  - docker
  - postgres

language: ruby

env:
  - GEM=. DB=postgres
  - GEM=decidim-admin DB=postgres
  - GEM=decidim-core DB=postgres
  - GEM=decidim-system DB=postgres
  - GEM=decidim-api DB=postgres
  - GEM=decidim-pages DB=postgres

before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn
  - export BUNDLE_GEMFILE="$TRAVIS_BUILD_DIR/Gemfile"

cache:
  bundler: true
  directories:
  - $HOME/.yarn-cache

script:
  - yarn run eslint $GEM/app/**/*.js.es6 $GEM/app/**/*.js
  - cd $GEM;
  - $TRAVIS_BUILD_DIR/run_ci.sh

rvm:
  - 2.3.1

notifications:
    email: false

addons:
  postgresql: "9.4"
