sudo: required
dist: trusty

services:
  - docker
  - postgres

language: ruby

env:
  - GEM=. DB=postgres
  - GEM=decidim-admin DB=postgres
  - GEM=decidim-core DB=postgres
  - GEM=decidim-system DB=postgres
  - GEM=decidim-api DB=postgres
  - GEM=decidim-pages DB=postgres
  - GEM=decidim-comments DB=postgres

before_install:
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - yarn
  - export BUNDLE_GEMFILE="$TRAVIS_BUILD_DIR/Gemfile"

cache:
  bundler: true
  directories:
  - $HOME/.yarn-cache

script:
  - yarn run eslint $GEM/app/**/*.js.es6 $GEM/app/**/*.js
  - cd $GEM;
  - $TRAVIS_BUILD_DIR/run_ci.sh

rvm:
  - 2.3.3

notifications:
    email: false

addons:
  postgresql: "9.4"
