version: '3'
services:
  decidim:
    image: decidim/decidim-dev:latest
    entrypoint: /usr/local/bin/entrypoint.sh
    command: decidim
    working_dir: /code
    ports:
      - 3000:3000
    volumes:
      - .:/code
      - gems:/usr/local/bundle:delegated
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - BUNDLE_PATH=/usr/local/bundle
    links:
      - pg
      - redis
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  gems: {}
  pg-data: {}
  redis-data: {}
