# Disabled rspec configurations

RSpec/ExpectInHook:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

RSpecRails/NegationBeValid:
  Enabled: false

RSpec/MetadataStyle:
  Enabled: false

RSpec/RemoveConst:
  Enabled: false
