base_locale: en

ignore_unused:
- "decidim.features.budgets.name"
- "decidim.features.budgets.settings.*"
- "decidim.features.budgets.actions.*"
- "activemodel.attributes.project.*"
- "decidim.resource_links.*"
