base_locale: en
locales: [en]
ignore_unused:
- "decidim.features.results.name"
- "decidim.features.results.settings.*"
- "decidim.resource_links.*"
- activerecord.attributes.*
- activemodel.attributes.*