base_locale: en
locales: [en]
ignore_unused:
- "decidim.features.proposals.name"
- "decidim.features.proposals.settings.*"
- "decidim.resource_links.*"
- "activemodel.attributes.proposal.*"
- "decidim.proposals.answers.*"
