require: rubocop-capybara

Capybara:
  Enabled: true
  DocumentationBaseURL: https://docs.rubocop.org/rubocop-capybara
  Include: &1
    - "**/spec/**/*.rb"

Capybara/ClickLinkOrButtonStyle:
  Enabled: true

Capybara/NegationMatcher:
  Enabled: false

Capybara/RedundantWithinFind:
  Enabled: false

Capybara/RSpec:
  Enabled: false
  Include: *1

Capybara/RSpec/HaveSelector:
  Enabled: false
