require: rubocop-rspec

#  RSpec:
#    Patterns:
#      - "(?:^|/)spec/"
#      - "(?:^|/)test/"

RSpec/BeforeAfterAll:
  Enabled: true

RSpec/ContextWording:
  Enabled: true
  Prefixes:
    - when
    - with
    - without
    - and

RSpec/DescribeClass:
  Exclude:
    - spec/gemfiles_spec.rb
    - spec/webpacker_spec.rb
    - spec/version_files_spec.rb
    - spec/spellcheck_spec.rb
    - spec/i18n_spec.rb
    - "**/*/spec/**/*_badge_spec.rb"
    - "**/tasks/**/*"

RSpec/ExampleLength:
  Max: 49

RSpec/ExpectInHook:
  Enabled: false

RSpec/IteratedExpectation:
  Enabled: true

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 35

RSpec/NestedGroups:
  Max: 7

RSpec/NamedSubject:
  Enabled: false

RSpec/RepeatedExampleGroupDescription:
  Enabled: true

RSpec/RepeatedExampleGroupBody:
  Enabled: true

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false
