name: Backport Work
on:
  pull_request_target:
    types: ["labeled", "closed"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  CI: "true"
  RUBY_VERSION: 3.3.4

jobs:
  backport:
    name: "Backporter - test"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: >
      github.base_ref == 'develop' &&
      github.event.pull_request.merged &&
      !contains(github.event.pull_request.labels.*.name, 'no-backport')
      && (
        github.event.action == 'closed'
        || (
          github.event.action == 'labeled'
            && (contains(github.event.pull_request.labels.*.name, 'type: fix') || contains(github.event.label.name, 'type: fix') )
        )
      )
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - run: gem install decidim-maintainers_toolbox
        name: Install toolbox
      - run: |
          git config user.name "decidim-bot"
          git config user.email "23476292+decidim-bot@users.noreply.github.com"
        name: Setting git
      - run: decidim-action-backporter --github-token=${{ secrets.GITHUB_TOKEN }}  --pull_request_id=${{ github.event.pull_request.number }}
        name: Create
        shell: "bash"
