name: "[CI] Lint PR format"
on:
  pull_request:
    branches-ignore:
      - "chore/l10n*"
    types: [opened, edited, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check_title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          disallowed_prefixes: "feat/,feature/,fix/,chore/,build/,ci/,refactor/,docs/,wip/,fix:"
          prefix_case_sensitive: false
          regex: "^[A-Z].+"
          min_length: 5
          max_length: 100
